# Generated by Django 3.2.1 on 2021-06-06 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airports',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('airport_name', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='flights',
            fields=[
                ('flightno', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('business', models.IntegerField()),
                ('economy', models.IntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='ssdd_variance.airports')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='ssdd_variance.airports')),
            ],
        ),
    ]
