# Generated by Django 3.2.1 on 2021-06-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdd_variance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('mobile', models.IntegerField()),
                ('email_id', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
