# Generated by Django 3.2.1 on 2021-06-20 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssdd_variance', '0002_user_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departs',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('departure_time', models.CharField(max_length=64)),
                ('arrival_time', models.CharField(max_length=64)),
                ('arr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_code', to='ssdd_variance.airports')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_code', to='ssdd_variance.airports')),
                ('flight_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_code', to='ssdd_variance.flights')),
            ],
        ),
        migrations.CreateModel(
            name='passenger',
            fields=[
                ('adhaar_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('phone_no', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='user_login',
        ),
    ]
