# Generated by Django 3.2.3 on 2021-06-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssdd_variance', '0003_departs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_login',
        ),
    ]
