# Generated by Django 3.2.3 on 2021-06-17 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ssdd_variance', '0004_delete_user_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mail', to=settings.AUTH_USER_MODEL)),
                ('first_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fname', to=settings.AUTH_USER_MODEL)),
                ('last_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lname', to=settings.AUTH_USER_MODEL)),
                ('password', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passw', to=settings.AUTH_USER_MODEL)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uname', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
