# Generated by Django 3.2.1 on 2021-06-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssdd_variance', '0003_auto_20210620_1239'),
        ('ssdd_variance', '0005_user_login'),
    ]

    operations = [
    ]
